### ISSUE TITLE
As a user, I want to be able to make a visualization by selecting one or more data fields so that I can pick the variables that matter to me.

### ISSUE THREAD

**Issue by scimap** [cns-iu/aisl#10]

**Comment by katyb** [comment]
Pick and map (=assign data columns to reference system axis labels or color/size/shape coding)
k


--
Katy Borner
Victor H. Yngve Distinguished Professor of Engineering and Information Science
Director, CI for Network Science Center, http://cns.iu.edu
Curator, Mapping Science exhibit, http://scimaps.org

ISE and ILS, School of Informatics and Computing, Indiana University
Wells Library 021, 1320 E. Tenth Street, Bloomington, IN 47405, USA
Phone: (812) 855-3256  Fax: -6166

**Comment by scimap** [comment]
Issue moved to [cns-iu/xmacroscope #52](https://github.com/cns-iu/xmacroscope/issues/52) via [**ZenHub**](https://www.zenhub.com/)
