### ISSUE TITLE
RxDB initialization failure

### ISSUE THREAD

**Issue by Simpsoah** [cns-iu/aisl#18]
Running the ng dev server results in the following error, preventing the build from finishing. 

> ERROR in src/app/aisl-backend/shared/rxdb-database.service.ts(46,1): error TS2554: Expected 1 arguments, but got 0.

Temporarily fixed by adding an arbitrary argument to RxDB.QueryChangeDetector.enable();

**Comment by bherr2** [comment]
Odd, because enable takes an optional arg: https://github.com/pubkey/rxdb/blob/master/src/query-change-detector.js#L307

Can you attach the output of `> npm list`? I wonder if its a versioning thing (I'm guessing tsc, but not sure)

**Comment by bherr2** [comment]
@Simpsoah can you try pulling from master and doing an npm install?

**Comment by bherr2** [comment]
As far as I can tell this is fixed in master. Closing this now, but will re-open if the problem persists.
