### ISSUE TITLE
Drag/Drop is not working properly in Firefox (58)

### ISSUE THREAD

**Issue by bherr2** [cns-iu/aisl#39]
Current issue is when dropping from a drag onto an acceptable dropzone, the url changes to "about:blank" and says this:

Hmm. That address doesn’t look right.
Please check that the URL is correct and try again.

Don't close this issue until I can confirm its working.

**Comment by Gruski** [comment]
Still having this problem on Firefox v68. When will this be fixed?

**Comment by bherr2** [comment]
We moved this repo to [cns-iu/xmacroscope](https://github.com/cns-iu/xmacroscope) and I believe it was fixed. Can you check [the demo site](https://cns-iu.github.io/xmacroscope/#/mav)?

Also, in the next revision of the UI, we will be completely removing drag/drop and using simple button presses to make things easier to understand.
